### ISSUE TITLE
Add support for "projects" block

### ISSUE THREAD

**Issue by asm0dey** [thibaudcolas/jsonresume-theme-eloquent#14]

**Comment by thibaudcolas** [comment]
Hey @asm0dey, it's not super clear to me what you're after. The `volunteer` section is already labeled "Projects" in the resume UI, and JSON schema has no `projects` block that I know of (see https://jsonresume.org/schema/).

**Comment by asm0dey** [comment]
Sorry, but you're wrong. Schema is just not updated on site, but is updated in github: https://github.com/jsonresume/resume-schema/blob/v1.0.0/schema.json

Projects are for conferences and so on, volunteering is for volunteering only.

**Comment by thibaudcolas** [comment]
Ah cool, no need to be sorry. That's unreleased though as far as I can tell, the latest release still being 0.0.16.

For projects vs `volunteer` – yep, I'm aware of that. Although in the absence of a (released) `projects` section, I think that's as good as it gets.

**Comment by asm0dey** [comment]
OK, thanks!
