### ISSUE TITLE
Locality issue with dates 

### ISSUE THREAD

**Issue by benthemonkey** [thibaudcolas/jsonresume-theme-eloquent#2]
Hey, I really love this theme!

I noticed that, for some reason, if I put a date like "2015-05-01" in a field, it would get rendered as the previous month ("April 2015" in this case). I tracked down the problem to the following behavior in Node (v0.12.7):

``` node
> new Date('2015-07-01').toString()
'Tue Jun 30 2015 19:00:00 GMT-0500 (CDT)'
```

I fixed the issue by simply passing the date string directly to `moment` (as in, `moment(date).format(format)`), which I think provides a wrapper around `new Date(string)` (http://momentjs.com/docs/#/parsing/string/). The problem was also resolved when I included a timezone in my dates (e.g. "2015-05-01 CDT")

I'm not sure if other people are running into the same issue, but if you get a chance I'd appreciate if you could look into this. Thanks!

**Comment by thibaudcolas** [comment]
Hey @benthemonkey, thanks for taking the time to report this.

I implemented your suggestion, and it seems to be working just fine. I just released the fix to npm (among other small changes) if you want to give it a try (`npm install --save jsonresume-theme-eloquent@2.0.0`).

I think it had to do with Node/JavaScript's handling of timezones when parsing dates. `Date` uses the system timezone if none is specified, which is not what we want in this specific case (we want to ignore timezones, which amounts to using UTC, as moment does). Here's some debugging code for reference:

``` js
var formatDate = function(date, format) {
    date = Handlebars.escapeExpression(date || '');
    process.env.TZ = 'America/Chicago';
    console.log(date, new Date(date), moment(date).format());
    date = moment(date).format(format);
    return new Handlebars.SafeString(date);
};
```
